name: jpword_app
description: A new Flutter application.
publish_to: 'none'
version: 1.3.4+1.3.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  # Admob
  google_mobile_ads: ^1.2.0
  # Text to Speech
  flutter_tts: ^3.2.1
  # App Icon
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.3

flutter_native_splash:
  image: "assets/icon/splush.png"
  color: "0077ff"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "0077ff"
  adaptive_icon_foreground: "assets/icon/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: Hiragino
      fonts:
        - asset: assets/fonts/hiraginokakugothicw3.ttc
    - family: Kodomo
      fonts:
        - asset: assets/fonts/KodomoRounded-Light.otf


