name: jpword_app
description: A new Flutter application.
publish_to: 'none'
version: 1.4.2+1.4.2

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter

  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  # Firebase Analytics
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  # Admob
  google_mobile_ads: ^5.1.0
  app_tracking_transparency: ^2.0.6
  # Text to Speech
  flutter_tts: ^4.0.2
  #env
  flutter_dotenv: ^5.1.0
  #MVVM
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # App Splash
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  image: "assets/icon/splash.png"
  color: "#0077ff"
  android_12:
    image: "assets/icon/appIcon.png"
    icon_background_color: "#0077ff"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0077ff"
  adaptive_icon_foreground: "assets/icon/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/.env
  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: Hiragino
      fonts:
        - asset: assets/fonts/hiraginokakugothicw3.ttc
    - family: Kodomo
      fonts:
        - asset: assets/fonts/KodomoRounded-Light.otf


