name: jpword_app
description: A new Flutter application.
publish_to: 'none'
version: 1.3.1+1.3.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Admob
  admob_flutter: ^2.0.0-nullsafety.1
  # Text to Speech
  flutter_tts: ^3.2.1
  # App Icon
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8

flutter:

  uses-material-design: true
  assets:
    - assets/image/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/appicon.png"

flutter_native_splash:
  image: assets/icon/splush.png
  color: "0077ff"

